stages:
- mavenbuild
- maventest
- autodeploy

maven-build:
        stage: mavenbuild
        tags:
        - shell
        script:
        - cd BackEnd/CydeNSeek
        - mvn package -B

maven-test:
        stage: maventest
        tags:
        - shell
        script:
        - cd BackEnd/CydeNSeek
        - mvn test
        artifacts:
                paths:
                - BackEnd/CydeNSeek/target/*.jar

autoDeploy:
        stage: autodeploy
        tags:
        - shell
        script:
        - cd BackEnd/CydeNSeek
        - mvn package
        - sudo mv target/*.jar /target/CydeNSeek.jar
        - sudo systemctl stop systemd-cydenseek
        - sudo systemctl start systemd-cydenseek
